[package]
name = "rrt"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra.workspace = true
bitvec = "1.0.1"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "kdtree"
harness = false
